"""initial schema

Revision ID: 7344a3f33550
Revises: 
Create Date: 2026-09-18 14:41:45.099545
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '7344a3f33550'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_checks',
    sa.Column('check_type', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('ruleset_version', sa.String(length=20), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_checks_checked_at'), 'compliance_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_compliance_checks_created_at'), 'compliance_checks', ['created_at'], unique=False)
    op.create_index('ix_compliance_checks_entity', 'compliance_checks', ['entity_type', 'entity_id', 'checked_at'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('scope', sa.String(length=60), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_scope_key')
    )
    op.create_index(op.f('ix_idempotency_keys_created_at'), 'idempotency_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_expires_at'), 'idempotency_keys', ['expires_at'], unique=False)
    op.create_index(op.f('ix_idempotency_keys_scope'), 'idempotency_keys', ['scope'], unique=False)
    op.create_table('notifications',
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_dedupe')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('primary_identifier_type', sa.Text(), nullable=True),
    sa.Column('primary_identifier_value', sa.String(length=64), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index('ix_products_brand_model', 'products', ['brand', 'model'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index('ix_products_primary_identifier', 'products', ['primary_identifier_value'], unique=False)
    op.create_table('provider_health',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('circuit_state', sa.String(length=20), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_failures', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('circuit_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', name='uq_provider_health_provider')
    )
    op.create_index(op.f('ix_provider_health_created_at'), 'provider_health', ['created_at'], unique=False)
    op.create_index(op.f('ix_provider_health_provider'), 'provider_health', ['provider'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_created_at'), 'settings', ['created_at'], unique=False)
    op.create_index('ix_settings_group', 'settings', ['group'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('old_state', sa.String(length=60), nullable=True),
    sa.Column('new_state', sa.String(length=60), nullable=True),
    sa.Column('request_id', sa.String(length=60), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_action_ts', 'audit_logs', ['action', 'occurred_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('competition_snapshots',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('competitor_count', sa.Integer(), nullable=False),
    sa.Column('seller_count', sa.Integer(), nullable=False),
    sa.Column('lowest_price', sa.BigInteger(), nullable=True),
    sa.Column('median_price', sa.BigInteger(), nullable=True),
    sa.Column('highest_price', sa.BigInteger(), nullable=True),
    sa.Column('realistic_sale_price', sa.BigInteger(), nullable=True),
    sa.Column('price_spread_ratio', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('listing_quality_score', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sold_last_30d', sa.Integer(), nullable=True),
    sa.Column('price_trend', sa.Text(), nullable=False),
    sa.Column('price_volatility', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_snapshots_observed_at'), 'competition_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_competition_snapshots_product_id'), 'competition_snapshots', ['product_id'], unique=False)
    op.create_index('ix_competition_snapshots_product_ts', 'competition_snapshots', ['product_id', 'observed_at'], unique=False)
    op.create_table('price_history',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('shipping_cost', sa.BigInteger(), nullable=True),
    sa.Column('lowest_price', sa.BigInteger(), nullable=True),
    sa.Column('median_price', sa.BigInteger(), nullable=True),
    sa.Column('highest_price', sa.BigInteger(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_history_entity_ts', 'price_history', ['entity_type', 'entity_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_price_history_observed_at'), 'price_history', ['observed_at'], unique=False)
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.create_index('ix_price_history_product_ts', 'price_history', ['product_id', 'observed_at'], unique=False)
    op.create_table('product_identifiers',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('identifier_type', sa.Text(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'identifier_type', 'value', name='uq_product_identifier')
    )
    op.create_index(op.f('ix_product_identifiers_created_at'), 'product_identifiers', ['created_at'], unique=False)
    op.create_index('ix_product_identifiers_lookup', 'product_identifiers', ['identifier_type', 'value'], unique=False)
    op.create_index(op.f('ix_product_identifiers_product_id'), 'product_identifiers', ['product_id'], unique=False)
    op.create_table('source_offers',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('seller_id', sa.String(length=80), nullable=True),
    sa.Column('seller_name', sa.String(length=160), nullable=True),
    sa.Column('sold_by_marketplace', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('shipping_cost', sa.BigInteger(), nullable=True),
    sa.Column('price_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('conditional_price', sa.BigInteger(), nullable=True),
    sa.Column('conditional_price_note', sa.Text(), nullable=True),
    sa.Column('stock_status', sa.Text(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('stock_confidence', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('inventory_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_order_quantity', sa.Integer(), nullable=True),
    sa.Column('delivery_min_days', sa.Integer(), nullable=True),
    sa.Column('delivery_max_days', sa.Integer(), nullable=True),
    sa.Column('delivery_speed', sa.Text(), nullable=False),
    sa.Column('delivery_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_fast_shipping_eligible', sa.Boolean(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', 'seller_id', name='uq_source_offer_external')
    )
    op.create_index(op.f('ix_source_offers_created_at'), 'source_offers', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_offers_external_id'), 'source_offers', ['external_id'], unique=False)
    op.create_index('ix_source_offers_price_ts', 'source_offers', ['price_timestamp'], unique=False)
    op.create_index(op.f('ix_source_offers_product_id'), 'source_offers', ['product_id'], unique=False)
    op.create_index('ix_source_offers_provider_active', 'source_offers', ['provider', 'is_active'], unique=False)
    op.create_table('target_listings',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=160), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('category_id', sa.String(length=40), nullable=True),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_own_listing', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('shipping_price', sa.BigInteger(), nullable=True),
    sa.Column('minimum_sale_price', sa.BigInteger(), nullable=True),
    sa.Column('recommended_sale_price', sa.BigInteger(), nullable=True),
    sa.Column('price_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('handling_time_days', sa.Integer(), nullable=True),
    sa.Column('delivery_expectation_days', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.String(length=80), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name='fk_target_listings_opportunity_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_target_listing_external')
    )
    op.create_index(op.f('ix_target_listings_created_at'), 'target_listings', ['created_at'], unique=False)
    op.create_index(op.f('ix_target_listings_external_id'), 'target_listings', ['external_id'], unique=False)
    op.create_index(op.f('ix_target_listings_opportunity_id'), 'target_listings', ['opportunity_id'], unique=False)
    op.create_index('ix_target_listings_price_ts', 'target_listings', ['price_timestamp'], unique=False)
    op.create_index(op.f('ix_target_listings_product_id'), 'target_listings', ['product_id'], unique=False)
    op.create_index('ix_target_listings_provider_state', 'target_listings', ['provider', 'state'], unique=False)
    op.create_index(op.f('ix_target_listings_sku'), 'target_listings', ['sku'], unique=False)
    op.create_table('delivery_estimates',
    sa.Column('source_offer_id', sa.Integer(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=True),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Text(), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipping_cost', sa.BigInteger(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['source_offer_id'], ['source_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_estimates_observed_at'), 'delivery_estimates', ['observed_at'], unique=False)
    op.create_index('ix_delivery_estimates_offer_ts', 'delivery_estimates', ['source_offer_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_delivery_estimates_source_offer_id'), 'delivery_estimates', ['source_offer_id'], unique=False)
    op.create_table('inventory_snapshots',
    sa.Column('source_offer_id', sa.Integer(), nullable=False),
    sa.Column('stock_status', sa.Text(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('stock_confidence', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['source_offer_id'], ['source_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_snapshots_observed_at'), 'inventory_snapshots', ['observed_at'], unique=False)
    op.create_index('ix_inventory_snapshots_offer_ts', 'inventory_snapshots', ['source_offer_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_inventory_snapshots_source_offer_id'), 'inventory_snapshots', ['source_offer_id'], unique=False)
    op.create_table('product_matches',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('source_offer_id', sa.Integer(), nullable=False),
    sa.Column('target_listing_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('matcher_version', sa.String(length=20), nullable=False),
    sa.Column('match_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('quantity_ratio', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_offer_id'], ['source_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_listing_id'], ['target_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_offer_id', 'target_listing_id', name='uq_match_offer_listing')
    )
    op.create_index(op.f('ix_product_matches_created_at'), 'product_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_product_matches_match_timestamp'), 'product_matches', ['match_timestamp'], unique=False)
    op.create_index(op.f('ix_product_matches_product_id'), 'product_matches', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_matches_source_offer_id'), 'product_matches', ['source_offer_id'], unique=False)
    op.create_index('ix_product_matches_status', 'product_matches', ['status', 'confidence'], unique=False)
    op.create_index(op.f('ix_product_matches_target_listing_id'), 'product_matches', ['target_listing_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('source_offer_id', sa.Integer(), nullable=True),
    sa.Column('target_listing_id', sa.Integer(), nullable=True),
    sa.Column('product_match_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('execution_mode', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('source_price', sa.BigInteger(), nullable=True),
    sa.Column('target_price', sa.BigInteger(), nullable=True),
    sa.Column('total_costs', sa.BigInteger(), nullable=True),
    sa.Column('expected_net_profit', sa.BigInteger(), nullable=True),
    sa.Column('worst_case_net_profit', sa.BigInteger(), nullable=True),
    sa.Column('best_case_net_profit', sa.BigInteger(), nullable=True),
    sa.Column('profit_margin', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('roi', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('capital_required', sa.BigInteger(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.Text(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('source_price_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_price_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inventory_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profit_calculation_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_revalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('decision_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('discovery_source', sa.String(length=60), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_match_id'], ['product_matches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_offer_id'], ['source_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_listing_id'], ['target_listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_actionable', 'opportunities', ['state', 'risk_score', 'match_confidence'], unique=False)
    op.create_index(op.f('ix_opportunities_created_at'), 'opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_opportunities_expected_net_profit'), 'opportunities', ['expected_net_profit'], unique=False)
    op.create_index('ix_opportunities_expires', 'opportunities', ['expires_at'], unique=False)
    op.create_index(op.f('ix_opportunities_product_id'), 'opportunities', ['product_id'], unique=False)
    op.create_index(op.f('ix_opportunities_reference'), 'opportunities', ['reference'], unique=True)
    op.create_index(op.f('ix_opportunities_risk_score'), 'opportunities', ['risk_score'], unique=False)
    op.create_index(op.f('ix_opportunities_source_offer_id'), 'opportunities', ['source_offer_id'], unique=False)
    op.create_index(op.f('ix_opportunities_state'), 'opportunities', ['state'], unique=False)
    op.create_index('ix_opportunities_state_profit', 'opportunities', ['state', 'expected_net_profit'], unique=False)
    op.create_index(op.f('ix_opportunities_target_listing_id'), 'opportunities', ['target_listing_id'], unique=False)
    op.create_table('orders',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('target_listing_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_order_id', sa.String(length=80), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('execution_mode', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.BigInteger(), nullable=False),
    sa.Column('buyer_shipping_paid', sa.BigInteger(), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buyer_reference', sa.String(length=120), nullable=True),
    sa.Column('ship_to', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('buyer_delivery_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_net_profit', sa.BigInteger(), nullable=True),
    sa.Column('worst_case_net_profit', sa.BigInteger(), nullable=True),
    sa.Column('expected_margin', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('expected_roi', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('capital_required', sa.BigInteger(), nullable=True),
    sa.Column('approved_source_unit_price', sa.BigInteger(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('realized_revenue', sa.BigInteger(), nullable=True),
    sa.Column('realized_source_cost', sa.BigInteger(), nullable=True),
    sa.Column('realized_fees', sa.BigInteger(), nullable=True),
    sa.Column('realized_shipping', sa.BigInteger(), nullable=True),
    sa.Column('realized_packaging', sa.BigInteger(), nullable=True),
    sa.Column('realized_return_cost', sa.BigInteger(), nullable=True),
    sa.Column('realized_other_costs', sa.BigInteger(), nullable=True),
    sa.Column('realized_net_profit', sa.BigInteger(), nullable=True),
    sa.Column('profit_variance', sa.BigInteger(), nullable=True),
    sa.Column('revalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revalidation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_required_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approval_note', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_listing_id'], ['target_listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_order_id', name='uq_order_external')
    )
    op.create_index('ix_orders_approval', 'orders', ['state', 'approval_required_at'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_external_order_id'), 'orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_orders_opportunity_id'), 'orders', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_orders_reference'), 'orders', ['reference'], unique=True)
    op.create_index(op.f('ix_orders_state'), 'orders', ['state'], unique=False)
    op.create_index('ix_orders_state_created', 'orders', ['state', 'created_at'], unique=False)
    op.create_table('capital_reservations',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'purpose', name='uq_capital_reservation_order_purpose')
    )
    op.create_index(op.f('ix_capital_reservations_created_at'), 'capital_reservations', ['created_at'], unique=False)
    op.create_index(op.f('ix_capital_reservations_order_id'), 'capital_reservations', ['order_id'], unique=False)
    op.create_index('ix_capital_reservations_state', 'capital_reservations', ['state'], unique=False)
    op.create_table('fulfillment_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('external_reference', sa.String(length=80), nullable=True),
    sa.Column('original_package', sa.Boolean(), nullable=True),
    sa.Column('received_condition', sa.Text(), nullable=True),
    sa.Column('repack_required', sa.Boolean(), nullable=False),
    sa.Column('repacked', sa.Boolean(), nullable=False),
    sa.Column('packaging_type', sa.String(length=60), nullable=True),
    sa.Column('package_length_cm', sa.Integer(), nullable=True),
    sa.Column('package_width_cm', sa.Integer(), nullable=True),
    sa.Column('package_height_cm', sa.Integer(), nullable=True),
    sa.Column('package_weight_grams', sa.Integer(), nullable=True),
    sa.Column('packaging_cost', sa.BigInteger(), nullable=False),
    sa.Column('provider_fees', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fee_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_fulfillment_order_order')
    )
    op.create_index(op.f('ix_fulfillment_orders_created_at'), 'fulfillment_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_fulfillment_orders_order_id'), 'fulfillment_orders', ['order_id'], unique=False)
    op.create_index('ix_fulfillment_orders_state', 'fulfillment_orders', ['state'], unique=False)
    op.create_table('order_events',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('from_state', sa.Text(), nullable=True),
    sa.Column('to_state', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'idempotency_key', name='uq_order_event_idempotency')
    )
    op.create_index(op.f('ix_order_events_event_type'), 'order_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_order_events_occurred_at'), 'order_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_index('ix_order_events_order_ts', 'order_events', ['order_id', 'occurred_at'], unique=False)
    op.create_table('profit_calculations',
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sale_revenue', sa.BigInteger(), nullable=False),
    sa.Column('buyer_shipping_paid', sa.BigInteger(), nullable=False),
    sa.Column('source_purchase_cost', sa.BigInteger(), nullable=False),
    sa.Column('source_shipping_cost', sa.BigInteger(), nullable=False),
    sa.Column('marketplace_fees', sa.BigInteger(), nullable=False),
    sa.Column('payment_fees', sa.BigInteger(), nullable=False),
    sa.Column('fulfillment_cost', sa.BigInteger(), nullable=False),
    sa.Column('outbound_shipping_cost', sa.BigInteger(), nullable=False),
    sa.Column('packaging_cost', sa.BigInteger(), nullable=False),
    sa.Column('expected_return_cost', sa.BigInteger(), nullable=False),
    sa.Column('risk_reserve', sa.BigInteger(), nullable=False),
    sa.Column('other_variable_costs', sa.BigInteger(), nullable=False),
    sa.Column('total_costs', sa.BigInteger(), nullable=False),
    sa.Column('net_profit', sa.BigInteger(), nullable=False),
    sa.Column('profit_margin', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('roi', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('capital_required', sa.BigInteger(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fee_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profit_model_version', sa.String(length=20), nullable=False),
    sa.Column('fee_model_version', sa.String(length=20), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profit_calculations_calculated_at'), 'profit_calculations', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_profit_calculations_created_at'), 'profit_calculations', ['created_at'], unique=False)
    op.create_index('ix_profit_calculations_opp_scenario', 'profit_calculations', ['opportunity_id', 'scenario', 'calculated_at'], unique=False)
    op.create_index(op.f('ix_profit_calculations_opportunity_id'), 'profit_calculations', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_profit_calculations_order_id'), 'profit_calculations', ['order_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blockers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_reserve_amount', sa.BigInteger(), nullable=True),
    sa.Column('risk_model_version', sa.String(length=20), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_assessed_at'), 'risk_assessments', ['assessed_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_created_at'), 'risk_assessments', ['created_at'], unique=False)
    op.create_index('ix_risk_assessments_opp_ts', 'risk_assessments', ['opportunity_id', 'assessed_at'], unique=False)
    op.create_index(op.f('ix_risk_assessments_opportunity_id'), 'risk_assessments', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_order_id'), 'risk_assessments', ['order_id'], unique=False)
    op.create_table('source_orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('source_offer_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_order_id', sa.String(length=80), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('execution_mode', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=True),
    sa.Column('shipping_cost', sa.BigInteger(), nullable=True),
    sa.Column('tax', sa.BigInteger(), nullable=True),
    sa.Column('total_cost', sa.BigInteger(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_number', sa.String(length=120), nullable=True),
    sa.Column('carrier', sa.String(length=80), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_offer_id'], ['source_offers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_source_order_idempotency')
    )
    op.create_index(op.f('ix_source_orders_created_at'), 'source_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_orders_external_order_id'), 'source_orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_source_orders_order_id'), 'source_orders', ['order_id'], unique=False)
    op.create_index('ix_source_orders_state', 'source_orders', ['state'], unique=False)
    op.create_table('shipments',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('fulfillment_order_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('carrier', sa.String(length=80), nullable=True),
    sa.Column('service', sa.String(length=80), nullable=True),
    sa.Column('tracking_number', sa.String(length=120), nullable=True),
    sa.Column('tracking_url', sa.Text(), nullable=True),
    sa.Column('origin', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('destination', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shipping_cost', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('label_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exception_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fulfillment_order_id'], ['fulfillment_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_shipment_idempotency')
    )
    op.create_index(op.f('ix_shipments_created_at'), 'shipments', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_index('ix_shipments_state', 'shipments', ['state'], unique=False)
    op.create_index('ix_shipments_tracking', 'shipments', ['carrier', 'tracking_number'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=False)
    op.create_table('warehouse_receipts',
    sa.Column('fulfillment_order_id', sa.Integer(), nullable=False),
    sa.Column('source_order_id', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_quantity', sa.Integer(), nullable=False),
    sa.Column('expected_quantity', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=80), nullable=True),
    sa.Column('tracking_number', sa.String(length=120), nullable=True),
    sa.Column('package_intact', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=80), nullable=True),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fulfillment_order_id'], ['fulfillment_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_order_id'], ['source_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_receipts_created_at'), 'warehouse_receipts', ['created_at'], unique=False)
    op.create_index(op.f('ix_warehouse_receipts_fulfillment_order_id'), 'warehouse_receipts', ['fulfillment_order_id'], unique=False)
    op.create_table('inspections',
    sa.Column('fulfillment_order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_receipt_id', sa.Integer(), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('inspected_by_user_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('sku_verified', sa.Boolean(), nullable=False),
    sa.Column('quantity_verified', sa.Boolean(), nullable=False),
    sa.Column('condition_verified', sa.Boolean(), nullable=False),
    sa.Column('accessories_verified', sa.Boolean(), nullable=False),
    sa.Column('expected_identifier', sa.String(length=64), nullable=True),
    sa.Column('observed_identifier', sa.String(length=64), nullable=True),
    sa.Column('observed_condition', sa.Text(), nullable=True),
    sa.Column('observed_quantity', sa.Integer(), nullable=True),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fulfillment_order_id'], ['fulfillment_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inspected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_receipt_id'], ['warehouse_receipts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_created_at'), 'inspections', ['created_at'], unique=False)
    op.create_index(op.f('ix_inspections_fulfillment_order_id'), 'inspections', ['fulfillment_order_id'], unique=False)
    op.create_table('returns',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_return_id', sa.String(length=80), nullable=True),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('buyer_comment', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('refund_amount', sa.BigInteger(), nullable=False),
    sa.Column('return_shipping_cost', sa.BigInteger(), nullable=False),
    sa.Column('restocking_recovery', sa.BigInteger(), nullable=False),
    sa.Column('fees_refunded', sa.BigInteger(), nullable=False),
    sa.Column('total_return_cost', sa.BigInteger(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspection_result', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_return_id', name='uq_return_external')
    )
    op.create_index(op.f('ix_returns_created_at'), 'returns', ['created_at'], unique=False)
    op.create_index(op.f('ix_returns_external_return_id'), 'returns', ['external_return_id'], unique=False)
    op.create_index(op.f('ix_returns_order_id'), 'returns', ['order_id'], unique=False)
    op.create_index('ix_returns_state', 'returns', ['state'], unique=False)
    # Circular dependency between opportunities and target_listings: this FK
    # is created after both tables exist (autogenerate skips use_alter FKs).
    op.create_foreign_key(
        "fk_target_listings_opportunity_id",
        "target_listings",
        "opportunities",
        ["opportunity_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_target_listings_opportunity_id", "target_listings", type_="foreignkey")
    op.drop_index('ix_returns_state', table_name='returns')
    op.drop_index(op.f('ix_returns_order_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_external_return_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_created_at'), table_name='returns')
    op.drop_table('returns')
    op.drop_index(op.f('ix_inspections_fulfillment_order_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_created_at'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_warehouse_receipts_fulfillment_order_id'), table_name='warehouse_receipts')
    op.drop_index(op.f('ix_warehouse_receipts_created_at'), table_name='warehouse_receipts')
    op.drop_table('warehouse_receipts')
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_index('ix_shipments_tracking', table_name='shipments')
    op.drop_index('ix_shipments_state', table_name='shipments')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_created_at'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_source_orders_state', table_name='source_orders')
    op.drop_index(op.f('ix_source_orders_order_id'), table_name='source_orders')
    op.drop_index(op.f('ix_source_orders_external_order_id'), table_name='source_orders')
    op.drop_index(op.f('ix_source_orders_created_at'), table_name='source_orders')
    op.drop_table('source_orders')
    op.drop_index(op.f('ix_risk_assessments_order_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_opportunity_id'), table_name='risk_assessments')
    op.drop_index('ix_risk_assessments_opp_ts', table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_created_at'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_assessed_at'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_profit_calculations_order_id'), table_name='profit_calculations')
    op.drop_index(op.f('ix_profit_calculations_opportunity_id'), table_name='profit_calculations')
    op.drop_index('ix_profit_calculations_opp_scenario', table_name='profit_calculations')
    op.drop_index(op.f('ix_profit_calculations_created_at'), table_name='profit_calculations')
    op.drop_index(op.f('ix_profit_calculations_calculated_at'), table_name='profit_calculations')
    op.drop_table('profit_calculations')
    op.drop_index('ix_order_events_order_ts', table_name='order_events')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_occurred_at'), table_name='order_events')
    op.drop_index(op.f('ix_order_events_event_type'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('ix_fulfillment_orders_state', table_name='fulfillment_orders')
    op.drop_index(op.f('ix_fulfillment_orders_order_id'), table_name='fulfillment_orders')
    op.drop_index(op.f('ix_fulfillment_orders_created_at'), table_name='fulfillment_orders')
    op.drop_table('fulfillment_orders')
    op.drop_index('ix_capital_reservations_state', table_name='capital_reservations')
    op.drop_index(op.f('ix_capital_reservations_order_id'), table_name='capital_reservations')
    op.drop_index(op.f('ix_capital_reservations_created_at'), table_name='capital_reservations')
    op.drop_table('capital_reservations')
    op.drop_index('ix_orders_state_created', table_name='orders')
    op.drop_index(op.f('ix_orders_state'), table_name='orders')
    op.drop_index(op.f('ix_orders_reference'), table_name='orders')
    op.drop_index(op.f('ix_orders_opportunity_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index('ix_orders_approval', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_opportunities_target_listing_id'), table_name='opportunities')
    op.drop_index('ix_opportunities_state_profit', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_state'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_source_offer_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_risk_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_reference'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_product_id'), table_name='opportunities')
    op.drop_index('ix_opportunities_expires', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_expected_net_profit'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_created_at'), table_name='opportunities')
    op.drop_index('ix_opportunities_actionable', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_product_matches_target_listing_id'), table_name='product_matches')
    op.drop_index('ix_product_matches_status', table_name='product_matches')
    op.drop_index(op.f('ix_product_matches_source_offer_id'), table_name='product_matches')
    op.drop_index(op.f('ix_product_matches_product_id'), table_name='product_matches')
    op.drop_index(op.f('ix_product_matches_match_timestamp'), table_name='product_matches')
    op.drop_index(op.f('ix_product_matches_created_at'), table_name='product_matches')
    op.drop_table('product_matches')
    op.drop_index(op.f('ix_inventory_snapshots_source_offer_id'), table_name='inventory_snapshots')
    op.drop_index('ix_inventory_snapshots_offer_ts', table_name='inventory_snapshots')
    op.drop_index(op.f('ix_inventory_snapshots_observed_at'), table_name='inventory_snapshots')
    op.drop_table('inventory_snapshots')
    op.drop_index(op.f('ix_delivery_estimates_source_offer_id'), table_name='delivery_estimates')
    op.drop_index('ix_delivery_estimates_offer_ts', table_name='delivery_estimates')
    op.drop_index(op.f('ix_delivery_estimates_observed_at'), table_name='delivery_estimates')
    op.drop_table('delivery_estimates')
    op.drop_index(op.f('ix_target_listings_sku'), table_name='target_listings')
    op.drop_index('ix_target_listings_provider_state', table_name='target_listings')
    op.drop_index(op.f('ix_target_listings_product_id'), table_name='target_listings')
    op.drop_index('ix_target_listings_price_ts', table_name='target_listings')
    op.drop_index(op.f('ix_target_listings_opportunity_id'), table_name='target_listings')
    op.drop_index(op.f('ix_target_listings_external_id'), table_name='target_listings')
    op.drop_index(op.f('ix_target_listings_created_at'), table_name='target_listings')
    op.drop_table('target_listings')
    op.drop_index('ix_source_offers_provider_active', table_name='source_offers')
    op.drop_index(op.f('ix_source_offers_product_id'), table_name='source_offers')
    op.drop_index('ix_source_offers_price_ts', table_name='source_offers')
    op.drop_index(op.f('ix_source_offers_external_id'), table_name='source_offers')
    op.drop_index(op.f('ix_source_offers_created_at'), table_name='source_offers')
    op.drop_table('source_offers')
    op.drop_index(op.f('ix_product_identifiers_product_id'), table_name='product_identifiers')
    op.drop_index('ix_product_identifiers_lookup', table_name='product_identifiers')
    op.drop_index(op.f('ix_product_identifiers_created_at'), table_name='product_identifiers')
    op.drop_table('product_identifiers')
    op.drop_index('ix_price_history_product_ts', table_name='price_history')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_observed_at'), table_name='price_history')
    op.drop_index('ix_price_history_entity_ts', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index('ix_competition_snapshots_product_ts', table_name='competition_snapshots')
    op.drop_index(op.f('ix_competition_snapshots_product_id'), table_name='competition_snapshots')
    op.drop_index(op.f('ix_competition_snapshots_observed_at'), table_name='competition_snapshots')
    op.drop_table('competition_snapshots')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_ts', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index('ix_settings_group', table_name='settings')
    op.drop_index(op.f('ix_settings_created_at'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_provider_health_provider'), table_name='provider_health')
    op.drop_index(op.f('ix_provider_health_created_at'), table_name='provider_health')
    op.drop_table('provider_health')
    op.drop_index('ix_products_primary_identifier', table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index('ix_products_brand_model', table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_idempotency_keys_scope'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_expires_at'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_created_at'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_compliance_checks_entity', table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_created_at'), table_name='compliance_checks')
    op.drop_index(op.f('ix_compliance_checks_checked_at'), table_name='compliance_checks')
    op.drop_table('compliance_checks')
    # ### end Alembic commands ###
