"""Deterministic demo catalogue.

The catalogue is chosen to exercise the decision logic, not to flatter it.
It contains clearly profitable items, items that fail the 20 EUR floor, an
out-of-stock item, a slow-delivery item, a variant trap (same brand and model,
different colour) and a price anomaly that looks like 100 EUR of free money
and is not.  Demo mode is therefore a test of the filters, not a showcase.

All values are strings so that they become :class:`~decimal.Decimal` without
ever passing through a float.
"""

from __future__ import annotations

from typing import Any

#: Each entry describes one product with its source offer and target market.
DEMO_CATALOG: list[dict[str, Any]] = [
    {
        "key": "headphones-xm5",
        "title": "Sony WH-1000XM5 Wireless Noise Cancelling Headphones, Black",
        "brand": "Sony",
        "manufacturer": "Sony",
        "model": "WH-1000XM5",
        "category": "Audio",
        "ean": "4548736134584",
        "mpn": "WH1000XM5B.CE7",
        "asin": "B09XS7JWHH",
        "attributes": {"color": "black", "variant": "standard", "region": "EU"},
        "image_urls": ["https://example.invalid/demo/xm5.jpg"],
        "source": {
            "price": "199.00",
            "shipping": "0.00",
            "stock": "IN_STOCK",
            "quantity": 42,
            "stock_confidence": "0.95",
            "delivery_min": 1,
            "delivery_max": 2,
            "speed": "FAST",
            "fast_eligible": True,
            "sold_by_marketplace": True,
        },
        "target": {
            "price": "319.00",
            "shipping": "0.00",
            "competitors": 11,
            "sellers": 9,
            "lowest": "309.00",
            "median": "319.00",
            "highest": "349.90",
            "realistic": "315.00",
            "sold_30d": 63,
            "volatility": "0.035",
        },
    },
    {
        "key": "espresso-machine",
        "title": "De'Longhi Dedica Style EC685.M Espresso Machine, Stainless Steel",
        "brand": "De'Longhi",
        "manufacturer": "De'Longhi",
        "model": "EC685.M",
        "category": "Kitchen",
        "ean": "8004399328198",
        "mpn": "EC685.M",
        "asin": "B01N0YAJTF",
        "attributes": {"color": "stainless steel", "capacity": "1.1 l", "region": "EU"},
        "image_urls": ["https://example.invalid/demo/ec685.jpg"],
        "source": {
            "price": "129.00",
            "shipping": "0.00",
            "stock": "IN_STOCK",
            "quantity": 18,
            "stock_confidence": "0.9",
            "delivery_min": 1,
            "delivery_max": 3,
            "speed": "FAST",
            "fast_eligible": True,
            "sold_by_marketplace": True,
        },
        "target": {
            "price": "219.90",
            "shipping": "0.00",
            "competitors": 7,
            "sellers": 6,
            "lowest": "209.00",
            "median": "218.00",
            "highest": "239.00",
            "realistic": "216.00",
            "sold_30d": 28,
            "volatility": "0.05",
        },
    },
    {
        "key": "robot-vacuum",
        "title": "Roborock Q5 Pro Robot Vacuum Cleaner, White",
        "brand": "Roborock",
        "manufacturer": "Roborock",
        "model": "Q5 Pro",
        "category": "Home",
        "ean": "6970995787283",
        "mpn": "Q5PRO-WHT",
        "asin": "B0C1J6H2QK",
        "attributes": {"color": "white", "variant": "Q5 Pro", "region": "EU"},
        "image_urls": ["https://example.invalid/demo/q5pro.jpg"],
        "source": {
            "price": "289.99",
            "shipping": "0.00",
            "stock": "LOW_STOCK",
            "quantity": 3,
            "stock_confidence": "0.55",
            "delivery_min": 2,
            "delivery_max": 4,
            "speed": "STANDARD",
            "fast_eligible": False,
            "sold_by_marketplace": False,
        },
        "target": {
            "price": "399.00",
            "shipping": "0.00",
            "competitors": 14,
            "sellers": 8,
            "lowest": "379.00",
            "median": "395.00",
            "highest": "449.00",
            "realistic": "389.00",
            "sold_30d": 41,
            "volatility": "0.11",
        },
    },
    {
        "key": "usb-c-cable",
        "title": "Anker PowerLine III USB-C to USB-C Cable 1.8 m, Black",
        "brand": "Anker",
        "manufacturer": "Anker",
        "model": "A8853",
        "category": "Accessories",
        "ean": "0194644045722",
        "mpn": "A8853H11",
        "asin": "B08HMWZBXC",
        "attributes": {"color": "black", "size": "1.8 m", "quantity": "1"},
        "image_urls": [],
        # Real but tiny margin: must be filtered out by the 20 EUR floor.
        "source": {
            "price": "12.99",
            "shipping": "0.00",
            "stock": "IN_STOCK",
            "quantity": 300,
            "stock_confidence": "0.98",
            "delivery_min": 1,
            "delivery_max": 2,
            "speed": "FAST",
            "fast_eligible": True,
            "sold_by_marketplace": True,
        },
        "target": {
            "price": "19.99",
            "shipping": "0.00",
            "competitors": 40,
            "sellers": 25,
            "lowest": "17.50",
            "median": "19.99",
            "highest": "24.99",
            "realistic": "19.50",
            "sold_30d": 210,
            "volatility": "0.04",
        },
    },
    {
        "key": "mechanical-keyboard",
        "title": "Keychron K8 Pro QMK/VIA Wireless Mechanical Keyboard, ISO-DE",
        "brand": "Keychron",
        "manufacturer": "Keychron",
        "model": "K8 Pro",
        "category": "Computing",
        "ean": "0742880690895",
        "mpn": "K8P-J3-DE",
        "asin": "B0B6ZQ2N4T",
        "attributes": {"layout": "ISO-DE", "color": "grey", "variant": "brown switch"},
        "image_urls": [],
        # Out of stock at source: must never become actionable.
        "source": {
            "price": "119.00",
            "shipping": "4.99",
            "stock": "OUT_OF_STOCK",
            "quantity": 0,
            "stock_confidence": "0.9",
            "delivery_min": None,
            "delivery_max": None,
            "speed": "UNKNOWN",
            "fast_eligible": False,
            "sold_by_marketplace": False,
        },
        "target": {
            "price": "179.00",
            "shipping": "0.00",
            "competitors": 5,
            "sellers": 4,
            "lowest": "169.00",
            "median": "178.00",
            "highest": "199.00",
            "realistic": "175.00",
            "sold_30d": 12,
            "volatility": "0.07",
        },
    },
    {
        "key": "camera-lens",
        "title": "Sigma 30mm F1.4 DC DN Contemporary Lens for Sony E-Mount",
        "brand": "Sigma",
        "manufacturer": "Sigma",
        "model": "30mm F1.4 DC DN",
        "category": "Photo",
        "ean": "0085126302658",
        "mpn": "302965",
        "asin": "B01LZP6T2X",
        "attributes": {"mount": "Sony E", "variant": "Contemporary", "region": "EU"},
        "image_urls": [],
        # Slow source delivery: fails the delivery feasibility check.
        "source": {
            "price": "229.00",
            "shipping": "0.00",
            "stock": "IN_STOCK",
            "quantity": 6,
            "stock_confidence": "0.8",
            "delivery_min": 7,
            "delivery_max": 12,
            "speed": "SLOW",
            "fast_eligible": False,
            "sold_by_marketplace": False,
        },
        "target": {
            "price": "319.00",
            "shipping": "0.00",
            "competitors": 9,
            "sellers": 7,
            "lowest": "305.00",
            "median": "318.00",
            "highest": "339.00",
            "realistic": "312.00",
            "sold_30d": 19,
            "volatility": "0.06",
        },
    },
    {
        "key": "designer-watch-anomaly",
        "title": "Citizen Eco-Drive Promaster Diver Watch BN0150-28E",
        "brand": "Citizen",
        "manufacturer": "Citizen",
        "model": "BN0150-28E",
        "category": "Watches",
        "ean": "4974374254191",
        "mpn": "BN0150-28E",
        "asin": "B00CVDPVWM",
        "attributes": {"color": "blue", "variant": "diver", "region": "EU"},
        "image_urls": [],
        # A 3.4x price ratio. Almost always a variant, bundle, condition or
        # regional difference rather than free money - the anomaly check must
        # route this to review instead of trusting it.
        "source": {
            "price": "139.00",
            "shipping": "0.00",
            "stock": "IN_STOCK",
            "quantity": 4,
            "stock_confidence": "0.7",
            "delivery_min": 1,
            "delivery_max": 3,
            "speed": "FAST",
            "fast_eligible": True,
            "sold_by_marketplace": False,
        },
        "target": {
            "price": "479.00",
            "shipping": "0.00",
            "competitors": 3,
            "sellers": 2,
            "lowest": "329.00",
            "median": "380.00",
            "highest": "479.00",
            "realistic": "349.00",
            "sold_30d": 4,
            "volatility": "0.28",
        },
    },
    {
        "key": "headphones-xm5-silver",
        "title": "Sony WH-1000XM5 Wireless Noise Cancelling Headphones, Silver",
        "brand": "Sony",
        "manufacturer": "Sony",
        "model": "WH-1000XM5",
        "category": "Audio",
        "ean": "4548736134607",
        "mpn": "WH1000XM5S.CE7",
        "asin": "B09XS7JWJG",
        # Same brand and model as the first entry, different colour. Any
        # matcher that trusts titles will cross-match these two.
        "attributes": {"color": "silver", "variant": "standard", "region": "EU"},
        "image_urls": [],
        "source": {
            "price": "245.00",
            "shipping": "0.00",
            "stock": "IN_STOCK",
            "quantity": 15,
            "stock_confidence": "0.9",
            "delivery_min": 1,
            "delivery_max": 2,
            "speed": "FAST",
            "fast_eligible": True,
            "sold_by_marketplace": True,
        },
        "target": {
            "price": "312.00",
            "shipping": "0.00",
            "competitors": 8,
            "sellers": 7,
            "lowest": "299.00",
            "median": "310.00",
            "highest": "329.00",
            "realistic": "308.00",
            "sold_30d": 22,
            "volatility": "0.04",
        },
    },
    {
        "key": "garden-hose",
        "title": "Gardena Comfort FLEX Garden Hose 20 m, 13 mm",
        "brand": "Gardena",
        "manufacturer": "Gardena",
        "model": "18034-20",
        "category": "Garden",
        "ean": "4078500018036",
        "mpn": "18034-20",
        "asin": "B0043D2E8O",
        "attributes": {"size": "20 m", "variant": "13 mm", "color": "grey"},
        "image_urls": [],
        "source": {
            "price": "44.99",
            "shipping": "0.00",
            "stock": "IN_STOCK",
            "quantity": 55,
            "stock_confidence": "0.92",
            "delivery_min": 1,
            "delivery_max": 3,
            "speed": "FAST",
            "fast_eligible": True,
            "sold_by_marketplace": True,
        },
        "target": {
            "price": "79.90",
            "shipping": "4.99",
            "competitors": 12,
            "sellers": 10,
            "lowest": "72.00",
            "median": "78.50",
            "highest": "89.00",
            "realistic": "77.00",
            "sold_30d": 34,
            "volatility": "0.05",
        },
    },
    {
        "key": "monitor-27",
        "title": "Dell S2722DC 27 inch QHD USB-C Monitor",
        "brand": "Dell",
        "manufacturer": "Dell",
        "model": "S2722DC",
        "category": "Computing",
        "ean": "5397184609941",
        "mpn": "S2722DC",
        "asin": "B09HMV6PLL",
        "attributes": {"size": "27 inch", "variant": "QHD", "color": "silver"},
        "image_urls": [],
        "source": {
            "price": "235.00",
            "shipping": "0.00",
            "stock": "IN_STOCK",
            "quantity": 9,
            "stock_confidence": "0.85",
            "delivery_min": 2,
            "delivery_max": 3,
            "speed": "STANDARD",
            "fast_eligible": True,
            "sold_by_marketplace": True,
        },
        "target": {
            "price": "369.00",
            "shipping": "0.00",
            "competitors": 10,
            "sellers": 8,
            "lowest": "355.00",
            "median": "368.00",
            "highest": "399.00",
            "realistic": "364.00",
            "sold_30d": 25,
            "volatility": "0.045",
        },
    },
]


def catalog_by_key() -> dict[str, dict[str, Any]]:
    return {entry["key"]: entry for entry in DEMO_CATALOG}


def source_external_id(entry: dict[str, Any]) -> str:
    return f"AMZ-{entry['asin']}"


def target_external_id(entry: dict[str, Any]) -> str:
    return f"EBAY-{entry['key'].upper()}"
